export const ACTION_CREATED = 'ACTION_CREATED';
export const ACTIONS_FETCHED = 'ACTIONS_FETCHED';
export const ACTION_FETCHED = 'ACTION_FETCHED';
export const ACTION_UPDATED = 'ACTION_UPDATED';
export const ACTION_DELETED = 'ACTION_DELETED';

export const ACTIVATIONS_FETCHED = 'ACTIVATIONS_FETCHED';
export const ACTIVATION_FETCHED = 'ACTIVATION_FETCHED';

export const TRIGGER_CREATED = 'TRIGGER_CREATED';
export const TRIGGERS_FETCHED = 'TRIGGERS_FETCHED';
export const TRIGGER_FETCHED = 'TRIGGER_FETCHED';
export const TRIGGER_UPDATED = 'TRIGGER_UPDATED';
export const TRIGGER_DELETED = 'TRIGGER_DELETED';
export const TRIGGER_FIRED = 'TRIGGER_FIRED';

export const RULE_CREATED = 'RULE_CREATED';
export const RULES_FETCHED = 'RULES_FETCHED';
export const RULE_FETCHED = 'RULE_FETCHED';
export const RULE_UPDATED = 'RULE_UPDATED';
export const RULE_DELETED = 'RULE_DELETED';

export const PACKAGES_FETCHED = 'PACKAGES_FETCHED';

export const START_REQUEST = 'START_REQUEST';